# Database
spring.datasource.url=postgresql://postgres:[YOUR-PASSWORD]@db.iocckltpuoveofpvhpmd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
openai.api.key=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
# Server
server.port=8080
